# Generated by Django 3.1.4 on 2021-05-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcf_test_app", "0003_auto_20210509_0128"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ThirdParty",
        ),
    ]
