version: "3"
services:
  dcf-test-ubuntu-base:
    build:
      context: .
      dockerfile: ubuntu-base.dockerfile
    image: dcf-test-ubuntu-base

  dcf-test-example:
    image: dcf-test-ubuntu-base
    volumes:
      - ./dcf-backend-example/overwrite:/_overwrite:ro
      - ./dcf-backend-example/entrypoint.py:/entrypoint.py:ro
      - ./dcf-backend-example/_out:/_out # build output
      - ../:/django_client_framework:ro
    command: ["python3", /entrypoint.py]

  dcf-test-example-ts:
    image: dcf-test-ubuntu-base
    volumes:
      - ../:/django_client_framework:ro
      - ../clients/django-client-framework-typescript:/django-client-framework-typescript:ro
      - ./dcf-backend-example/_out/dcf-backend-example.tar.gz:/dcf-backend-example.tar.gz:ro
      - ./dcf-client-typescript-example/proj:/proj:ro
      - ./dcf-client-typescript-example/entrypoint.py:/entrypoint.py:ro
      - ./dcf-client-typescript-example/_out:/_out # build output
    command: ["python3", /entrypoint.py]
