on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      DOCKER_LOGIN_PASSWD: ${{ secrets.YLILARRY_DOCKERHUB_TOKEN }}

    steps:
      - name: Display runner status
        run: |
          echo "hostname -f: $(hostname -f)"
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"

      - name: Run git checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          clean: true
          fetch-depth: 2
          submodules: recursive

      - name: Set up env vars
        run: |
          .github/workflows/set_env
          .github/workflows/set_env -w

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main
          title: "main <- ${BRANCH_NAME}: ${COMMIT_TITLE}"
